### ISSUE TITLE
set default editor to nano or something else

### ISSUE THREAD

**Issue by Vosjedev** [anki-code/xontrib-onepath#3]
please add the option to set default text editor from vim to a custom command.  
i want to use nano.

sorry if i can already do this by setting multiple things to nano instead of vim.
i am lazy. : (

**Comment by Vosjedev** [comment]
i closed. i want to bring attention to this, but it is not a problem without it.
you can ask to reopen this or reopen this if you want to implement this.

**Comment by Vosjedev** [comment]
o wow sorry just now realised it is already here.
`$XONTRIB_ONEPATH_ACTIONS['text/'] = 'nano'`

**Comment by anki-code** [comment]
If you like the idea click ⭐ on the repo
