### ISSUE TITLE
cant use `MIME type/subtype` when something is set for `MIME type/`

### ISSUE THREAD

**Issue by Vosjedev** [anki-code/xontrib-onepath#4]
i am trying to make onepath open glow on markdown files and nano on other text files. i did this with the following code:  
```  
$XONTRIB_ONEPATH_ACTIONS['text/'] = 'nano'
$XONTRIB_ONEPATH_ACTIONS['text/markdown'] = 'glow'
```  
but it always opens nano, even on markdown files.  
`$XONTRIB_ONEPATH_ACTIONS['*.md'] = 'glow'` is also ignored

the examples from the readme:
```
$XONTRIB_ONEPATH_ACTIONS['*.log'] = 'tail'           # tail for text type *.log files
$XONTRIB_ONEPATH_ACTIONS['text/plain.txt'] = 'less'  # less for plain text *.txt files
```
do not work, when paired with `$XONTRIB_ONEPATH_ACTIONS['text/'] = 'nano'` files with .log extenstion and plain files with txt extention still open nano...

this means you cant do anything with `text/type` as `text/` is set by default.

**Comment by anki-code** [comment]
Hello!
First of all the new release 0.4.0 with debug mode is here, please update:
```xsh
xpip install -U xontrib-onepath
```
Then use debug mode to solve your case:
```xsh
xontrib load onepath
$XONTRIB_ONEPATH_DEBUG = True
$XONTRIB_ONEPATH_ACTIONS['*.md'] = 'nano'  # higher priority than `text/`
$XONTRIB_ONEPATH_ACTIONS['text/'] = 'vim'  # lower priority than `*.md`

$XONTRIB_ONEPATH_ACTIONS
# {'<DIR>': 'cd', '<XFILE>': '<RUN>', '*.md': 'nano', 'text/': 'vim'}

cd /tmp
echo 123 > 123.md

123.md
# xontrib-onepath: types for /private/tmp/1.md:
# {'full_path': '/private/tmp/1.md',
#  'path_filename': '1.md',
#  'path_suffix_key': '*.md',
#  'file_type_suffix': 'text/plain.md',
#  'file_type': 'text/plain',
#  'file_type_group': 'text/',
#  'file_or_dir': '<FILE>',
#  'xfile': '<NX>',
#  'any': '*'}
# xontrib-onepath: selected action for /private/tmp/1.md: name='path_suffix_key', type='*.md', action='nano'
```
It works as expected.

Note that the `$XONTRIB_ONEPATH_ACTIONS` list has order and also types have order. The order is the priority.

**Comment by Vosjedev** [comment]
> Note that the $XONTRIB_ONEPATH_ACTIONS list has order and also types have order. The order is the priority.  

oh, oke. didn't know that. that was the problem. thanks!
